### PR TITLE
New documentation generated using pydoctor. Based on autokey/autokey …

### PR DESCRIPTION
**Pull request by sebastiansam55**
…commit https://github.com/autokey/autokey/commit/8ef5a71633bb1c62993077ad36801d22fe1f84e9

Album of changes.
Screenshot from 2020-11-03 23-17-39
Screenshot from 2020-11-03 23-17-47
Screenshot from 2020-11-03 23-17-59
Screenshot from 2020-11-03 23-18-15

### CODE REVIEW

**Comment by sebastiansam55** [comment]
For future reference the process for documentation is;
`cd <base autokey directory>`
`pydoctor --add-package=lib/autokey/scripting --html-output=/dir/to/autokey.github.io/repo`

Lots of other features in pydoctor that might be worth exploring.

**Comment by josephj11** [comment]
This is cool. What I am hoping to end up with is a new version of [this](https://autokey.github.io/index.html), including the changes you have made. It looks like you have generated part of that above.

**Comment by sebastiansam55** [comment]
I hosted the documentation so you can better see what the end result will look like. Both are based on the latest autokey/autokey for the develop and master branches.
https://sebastiansam55.github.io/autokey-develop/
https://sebastiansam55.github.io/autokey-master/

**Comment by josephj11** [comment]
This is a step in the right direction, but I find it really hard to navigate through the results. The old version is much less verbose and takes you right to the API call you're looking for. If we run this output through awk or something similar to extract the usage parts, that might work.

E.G. I just saw the open file dialog. Didn't know it was there. I have no idea how to use it. It appears to return a status and a file name string while I would have expected it to return something like a file descriptor or handle. It also has this remember as parameter and I have no clue as to how I would actually use it.

If I, as an experienced user, get this confused, it's likely that releasing this into the wild as is wouldn't be the best idea. Jack wrote our API examples wiki. That's the sort of thing we need. He or I can update it once we are clear on what has changed.

**Pull request closed without merging**
