### PR TITLE
Fix broken wiki link in Introduction.

### PR DESCRIPTION
**Pull request by Elliria**
Replace relative link with absolute link.

### CODE REVIEW

**Comment by Elliria** [comment]
This fixes the broken relative link to the wiki on the [Introduction](https://autokey.github.io/intro.html) page of the new documentation. Also, once this is merged in, its action will need to be run manually to apply the changes by rebuilding the documentation pages:
1. Go to [Build Autokey pages](https://github.com/autokey/autokey.github.io/actions/workflows/pages.yml)
2. Press the **Run** button
3. Wait for the process to finish.

**Comment by Elliria** [comment]
By the way, if you enable the wiki in this repository, I can put the steps for manually applying the changes into this repository's wiki and you'll know where to look if you ever need them or need to show them to someone else.

**Comment by Elliria** [comment]
Whoops. I renamed the wiki page after doing this PR, so now the link is no good. Will do this again.

**Comment by josephj11** [comment]
> By the way, if you enable the wiki in this repository, I can put the steps for manually applying the changes into this repository's wiki and you'll know where to look if you ever need them or need to show them to someone else.

I'm missing something. We have a wiki somewhere already. Where do you want this one...?

**Comment by Elliria** [comment]
This isn't the AutoKey repository. It's a completely different repository that was created specifically for the documentation. I figured that would be a good place to put its information so we will always be able to find it.

If you click **Settings** up in the toolbar at the top of the current window and scroll down to the **Features** section, I'll bet there isn't a check-mark in the **Wikis** box.

**Comment by josephj11** [comment]
OK. That was weird. The wiki was enabled, but empty. I added a dummy entry to be sure I could. See if you can get into it.

**Comment by Elliria** [comment]
I can read it, but can't edit it. To make the wiki editable, you'll want to go back into the settings and remove the check-mark from the **Restrict editing to collaborators only** box in the **Features** section.

**Comment by josephj11** [comment]
Took me a while to find it, but it should be unlocked now.

Also found the Sponsors section. Didn't touch it, but if we ever solve the accounting/management issues, that looks like a way for people to donate  via GitHub.

**Comment by Elliria** [comment]
It's working perfectly. I added a statement to the home page and created the [Maintenance](https://github.com/autokey/autokey.github.io/wiki/Maintenance) page that now contains the steps for updating the actions. Those will come in handy in case it's a long time before either of us does that again or in case someone new comes on board.

Interestingly, that wiki seems to have an automatic Table of Contents that doesn't need intervention by us. It auto-detected the new page and added it automatically.

**Comment by sebastiansam55** [comment]
It would make more sense to me to consolidate everything into the documentation website, github wikis are not great imo, not searchable and kinda hidden.

I understand that it is certianly easier to update the wiki than to push files to this repo but :shrug:

**Comment by Elliria** [comment]
Put it into a new section in the [README.md](https://github.com/autokey/autokey.github.io/blob/master/README.md) file?

**Comment by sebastiansam55** [comment]
yeah that'd be a perfect place for it

**Comment by josephj11** [comment]
I'm concerned about my workload getting significantly expanded by having to review and merge all the "wiki" updates.

I like it that people can add stuff without my intervention. This could be a problem if there were annoying or malicious editors, but so far, this has never happened.

**Comment by Elliria** [comment]
Okay, no problem. I added it to the [README.md](https://github.com/autokey/autokey.github.io/blob/master/README.md) file in PR #6 and once that's merged in, we can get rid of the wiki in this repository.

**Comment by josephj11** [comment]
I'm not sure we're on the same page. There are now two wikis - the old one and the one in this docs branch. I want the old one to stay as it is. This new one doesn't matter to me (yet). I want the one here to work whatever way is easiest to maintain. I don't see it getting very elaborate. Anything that might do that should probably be in the main wiki.

**Comment by Elliria** [comment]
We might be on the same page. I'm not sure. What I'm saying is that the [AutoKey wiki](https://github.com/autokey/autokey/wiki) that we've all been working on for years needs to remain and continue to be worked on, whereas AutoKey's [new documentation wiki](https://github.com/autokey/autokey.github.io/wiki) (this current repository's wiki that you can get to by clicking the **wiki** button at the top of this page) can now be gotten rid of since the information it contains that we need is now in the [README.md](https://github.com/autokey/autokey.github.io/blob/master/README.md) file in this repository.

I'd recommend clicking the **Settings** button at the top of this window and uncheck the **Wikis** and **Restrict editing to collaborators only** boxes, which will get rid of the wiki.

**Pull request closed without merging**
