### PR TITLE
switch documentation to sphinx-build

### PR DESCRIPTION
**Pull request by sebastiansam55**

### CODE REVIEW

**Comment by sebastiansam55** [comment]
Let me know if you have any questions about this.

You'll have to go into the pages settings and switch it to build from GitHub actions

If you give me that access to this repo I can do that as well

**Comment by josephj11** [comment]
This PR:

A lot of changes. I read through them, but don't understand a lot.
config.py 113  'github_user': 'sebastiansam55',
Is that correct for "production"?

intro.rst 55 - 61 needs to be updated for unhidden sidecar files, but that doesn't necessarily need to be done in this PR. Where does intro'.rst live? It doesn't look new, but it doesn't look that familiar either.

It appears that the new documentaton is created from the old epydoc format on the fly. That means that we definitely can't delete the old documentation. Is there a way to remove this dependency (later)? Ihe old docs are static and we'll eventually want to delete them (not any time soon).

What the heck is make.bat?  It looks like a Windows batch file.

I can do the "pages" thing after this is merged or you can do it. See below.

General:

FYI: I don't presume I know what I'm doing, so I don't merge any PRs until explicitly requested to do so.

@sebastiansam55 If you want admin access, just ask and I'll grant it (if I can figure out how).  :) I've done it before, so I'm sure it's pretty easy to do.

**Comment by sebastiansam55** [comment]
My b on missing that conf.py changes, I just updated that with the current year as well.

RE: intro.rst, we should get this PR/site live and then we can see use that page as an example to see how the workflow of using the "Edit on github" link on the pages would work in practice. Intro.rst is added to the Table of Contents in index.rst, on the live version of my repo it exists as https://sebastiansam55.github.io/autokey-sphinx/intro.html

Make.bat and the makefile were generated by the sphinx inital setup iirc (they've been there since I setup this up 2 years ago, I don't use them in any case). We can remove them, they're not hurting anything

The terminology gets pretty confusing, the syntax used in the autokey python source code is "epydoc style" markdown, epydoc in the context of this PR is not referring to the old documentation website. Sphinx has an extension that can translate "epydoc style" to RST (restructured text, which is what Sphinx uses, more feature rich markdown) on the fly so we can avoid going through and having to update all the autokey documentation for now, we can update that over time (but it's also not super important as it's well supported via thatextension).

The old autokey github documentation is generated by some epydoc program that hasn't been updated since 2008. 

I opened another PR on the main autokey/autokey repo with a github action to publish what is in that repo's /doc/scripting folder which is the same as this repo.

If the github actions don't work immediately I'll probably need access to tweak them/repo settings, they work in my repos (both this PR and the autokey/autokey action I wrote) but I've not done PRs related to Github actions before, there may be some additional caveats related to repo configuration that I'm not aware of.

For both repos you'll have to go into the Github Pages settings and switch them from publishing a folder to using the Github action option. You may also have to remove the existing "github-pages" environment listing before these github actions will be able to make a new one

**Comment by sebastiansam55** [comment]
@josephj11 
This should be good to merge, once it does it should trigger the Github Action and update the website (assuming you set the github pages to use github actions and have deleted the prexisting github-pages environment).

For the older style documentation on autokey/autokey I configured it to be manual run only so you'd have to run it manually after merging that PR, because that documentation will not be getting updated any time soon so it doesn't need automation

**Comment by josephj11** [comment]
All of this makes sense except for deleting  "the prexisting github-pages environment". Exactly what needs to be done?

IIUC, I should delete (whatever - see above), turn on GiiHub Actions for main and develop (and beta?) and then merge this PR.

**Comment by sebastiansam55** [comment]
Yes (or I had to do this in my repo which was a fork of this one) See pictures for where I found those settings. I think it's because the environment was automatically created by the Github pages native thing it can't be replaced by the Github action

Screenshot from 2023-03-18 10-47-13
Screenshot from 2023-03-18 10-48-47

**Comment by josephj11** [comment]
When I select GitHub Actions, it opens a dialog to configure jekyll. IDK what to do there. It starts with some sort of template.

**Comment by sebastiansam55** [comment]
Okay, do you want to try giving me access and I'll see if I can figure it
out?

**Comment by sebastiansam55** [comment]
Actually, if you're selecting the "Actions" tab that's not the correct location, it's doing that because there currently isn't any configured actions. Both the things you need to do are in the "Settings" tab like in my screenshot

**Comment by sebastiansam55** [comment]
@josephj11 
It looks like this repo is not listed in the Contributors group so I still don't have any access to it? I think if you add this repo to that group I should be able to make the changes needed

**Comment by josephj11** [comment]
Hopefully, you should have access now. I added it to the team.

**Pull request merged**
